import type { Metadata } from "next";
import { Geist, Alfa_Slab_One } from "next/font/google";
import "./globals.css";
import Navbar from "@/comoponents/Navbar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});


const alfaSlabOne = Alfa_Slab_One({
  variable: "--font-alfa-slab-one",
  subsets: ["latin"],
  weight: "400",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
   <html lang="en" className={`${geistSans.variable} ${alfaSlabOne.variable} font-[var(--font-geist-sans)]`}>
      <body >
        <Navbar />
        {children}
      </body>
    </html>
  );
}
